variables:
  RESTY_VERSION: 1.27.1.1
  RESTY_RELEASE: 148
  IMAGE_NAME: registry.hanada.info/hanada/openresty
  TAG: ${RESTY_VERSION}-${RESTY_RELEASE}

stages:
  - build
  - manifest

build-amd64:
  stage: build
  tags:
    - debian-x86_64
  only:
    refs:
      - main
  script:
    - >
      docker login -u "${NEXUS_USERNAME}" -p "${NEXUS_PASSWORD}" registry.hanada.info
    - >
      docker build \
        --build-arg RESTY_VERSION="${RESTY_VERSION}" \
        --build-arg RESTY_RELEASE="${RESTY_RELEASE}" \
        -t "${IMAGE_NAME}:${TAG}-amd64" \
        --push \
        .

build-arm64:
  stage: build
  tags:
    - debian-aarch64
  only:
    refs:
      - main
  script:
    - >
      docker login -u "${NEXUS_USERNAME}" -p "${NEXUS_PASSWORD}" registry.hanada.info
    - >
      docker build \
        --build-arg RESTY_VERSION="${RESTY_VERSION}" \
        --build-arg RESTY_RELEASE="${RESTY_RELEASE}" \
        -t "${IMAGE_NAME}:${TAG}-arm64" \
        --push \
        .

create-manifest:
  stage: manifest
  tags:
    - debian-x86_64
  needs:
    - build-amd64
    - build-arm64
  only:
    refs:
      - main
  script:
    - >
      docker login -u "${NEXUS_USERNAME}" -p "${NEXUS_PASSWORD}" registry.hanada.info
    - >
      docker manifest inspect "${IMAGE_NAME}:${TAG}-amd64" || exit 1
    - >
      docker manifest inspect "${IMAGE_NAME}:${TAG}-arm64" || exit 1
    - >
      docker manifest create --amend "${IMAGE_NAME}:${TAG}" \
        " ${IMAGE_NAME}:${TAG}-amd64" \
        "${IMAGE_NAME}:${TAG}-arm64"
    - >
      docker manifest push "${IMAGE_NAME}:${TAG}"
    - >
      docker manifest create "${IMAGE_NAME}" \
        "${IMAGE_NAME}:${TAG}-amd64" \
        "${IMAGE_NAME}:${TAG}-arm64"
    - >
      docker manifest push "${IMAGE_NAME}"
    #- >
    #  curl -u "${NEXUS_USERNAME}:${NEXUS_PASSWORD}" -X DELETE "https://registry.hanada.info/v2/hanada/openresty/manifests/$(docker inspect --format='{{index .RepoDigests 0}}' "${IMAGE_NAME}:${TAG}-amd64" | awk -F'@' '{print $2}')"
    #- >
    #  curl -u "${NEXUS_USERNAME}:${NEXUS_PASSWORD}" -X DELETE "https://registry.hanada.info/v2/hanada/openresty/manifests/$(docker inspect --format='{{index .RepoDigests 0}}' "${IMAGE_NAME}:${TAG}-arm64" | awk -F'@' '{print $2}')"