variables:
  RESTY_VERSION: 1.31.3.1
  RESTY_RELEASE: 344
  IMAGE_NAME: registry.hanada.info/openresty/openresty

stages:
  - build
  - manifest

build-amd64:
  stage: build
  tags:
    - debian-x86_64
  only:
    refs:
      - main
  script:
    - >
      docker build \
        --build-arg RESTY_VERSION="${RESTY_VERSION}" \
        --build-arg RESTY_RELEASE="${RESTY_RELEASE}" \
        -t "${IMAGE_NAME}:${RESTY_VERSION}.${RESTY_RELEASE}-amd64" \
        .
    - >
      docker login -u "${HARBOR_USERNAME}" -p "${HARBOR_PASSWORD}" registry.hanada.info
    - >
      docker push "${IMAGE_NAME}:${RESTY_VERSION}.${RESTY_RELEASE}-amd64"

build-arm64:
  stage: build
  tags:
    - debian-aarch64
  only:
    refs:
      - main
  script:
    - >
      docker build \
        --build-arg RESTY_VERSION="${RESTY_VERSION}" \
        --build-arg RESTY_RELEASE="${RESTY_RELEASE}" \
        -t "${IMAGE_NAME}:${RESTY_VERSION}.${RESTY_RELEASE}-arm64" \
        .
    - >
      docker login -u "${HARBOR_USERNAME}" -p "${HARBOR_PASSWORD}" registry.hanada.info
    - >
      docker push "${IMAGE_NAME}:${RESTY_VERSION}.${RESTY_RELEASE}-arm64"

create-manifest:
  stage: manifest
  tags:
    - debian-x86_64
  needs:
    - build-amd64
    - build-arm64
  only:
    refs:
      - main
  script:
    - >
      docker login -u "${HARBOR_USERNAME}" -p "${HARBOR_PASSWORD}" registry.hanada.info
    - >
      docker manifest inspect "${IMAGE_NAME}:${RESTY_VERSION}.${RESTY_RELEASE}-amd64" || exit 1
    - >
      docker manifest inspect "${IMAGE_NAME}:${RESTY_VERSION}.${RESTY_RELEASE}-arm64" || exit 1
    - >
      docker manifest create --amend "${IMAGE_NAME}:${RESTY_VERSION}.${RESTY_RELEASE}" \
        --amend "${IMAGE_NAME}:${RESTY_VERSION}.${RESTY_RELEASE}-amd64" \
        --amend "${IMAGE_NAME}:${RESTY_VERSION}.${RESTY_RELEASE}-arm64"
    - >
      docker manifest push --purge "${IMAGE_NAME}:${RESTY_VERSION}.${RESTY_RELEASE}"
    - >
      docker manifest create --amend "${IMAGE_NAME}" \
        --amend "${IMAGE_NAME}:${RESTY_VERSION}.${RESTY_RELEASE}-amd64" \
        --amend "${IMAGE_NAME}:${RESTY_VERSION}.${RESTY_RELEASE}-arm64"
    - >
      docker manifest push --purge "${IMAGE_NAME}"
