variables:
  RESTY_VERSION: 1.27.1.1
  RESTY_RELEASE: 158
  IMAGE_NAME: registry.hanada.info/hanada/openresty
  TAG: ${RESTY_VERSION}-${RESTY_RELEASE}

stages:
  - build
  - manifest

build-amd64:
  stage: build
  tags:
    - debian-x86_64
  only:
    refs:
      - main
  script:
    - >
      docker login -u "${NEXUS_USERNAME}" -p "${NEXUS_PASSWORD}" registry.hanada.info
    - >
      docker build \
        --build-arg RESTY_VERSION="${RESTY_VERSION}" \
        --build-arg RESTY_RELEASE="${RESTY_RELEASE}" \
        -t "${IMAGE_NAME}:${TAG}-amd64" \
        .
    - >
      docker push "${IMAGE_NAME}:${TAG}-amd64"

build-arm64:
  stage: build
  tags:
    - debian-aarch64
  only:
    refs:
      - main
  script:
    - >
      docker login -u "${NEXUS_USERNAME}" -p "${NEXUS_PASSWORD}" registry.hanada.info
    - >
      docker build \
        --build-arg RESTY_VERSION="${RESTY_VERSION}" \
        --build-arg RESTY_RELEASE="${RESTY_RELEASE}" \
        -t "${IMAGE_NAME}:${TAG}-arm64" \
        .
    - >
      docker push "${IMAGE_NAME}:${TAG}-arm64"

create-manifest:
  stage: manifest
  tags:
    - debian-x86_64
  needs:
    - build-amd64
    - build-arm64
  only:
    refs:
      - main
  script:
    - >
      docker login -u "${NEXUS_USERNAME}" -p "${NEXUS_PASSWORD}" registry.hanada.info
    - >
      docker manifest inspect "${IMAGE_NAME}:${TAG}-amd64" || exit 1
    - >
      docker manifest inspect "${IMAGE_NAME}:${TAG}-arm64" || exit 1
    - >
      docker manifest create --amend "${IMAGE_NAME}:${TAG}" \
        --amend "${IMAGE_NAME}:${TAG}-amd64" \
        --amend "${IMAGE_NAME}:${TAG}-arm64"
    - >
      docker manifest push --purge "${IMAGE_NAME}:${TAG}"
    - >
      docker manifest create --amend "${IMAGE_NAME}" \
        --amend "${IMAGE_NAME}:${TAG}-amd64" \
        --amend "${IMAGE_NAME}:${TAG}-arm64"
    - >
      docker manifest push --purge "${IMAGE_NAME}"