variables:
  RESTY_VERSION: 1.21.4.3
  RESTY_RELEASE: 15

stages:
  - build

docker-build:
  stage: build
  tags:
    - debian-x86_64
  only:
    refs:
      - main
  script:
    - >
      docker buildx build \
        --platform linux/amd64 \
        -t $CI_REGISTRY_IMAGE:latest \
        -t $CI_REGISTRY_IMAGE:$RESTY_VERSION-$RESTY_RELEASE \
        --build-arg RESTY_VERSION=$RESTY_VERSION \
        --build-arg RESTY_RELEASE=$RESTY_RELEASE \
        --push \
        .
