variables:
  RESTY_VERSION: 1.27.1.1
  RESTY_RELEASE: 141

stages:
  - build

build:
  stage: build
  tags:
    - debian-x86_64
  only:
    refs:
      - main
  script:
    - >
      docker buildx build \
        --platform linux/amd64,linux/arm64 \
        -t registry.hanada.info/hanada/openresty \
        -t registry.hanada.info/hanada/openresty:$RESTY_VERSION-$RESTY_RELEASE \
        --build-arg RESTY_VERSION=$RESTY_VERSION \
        --build-arg RESTY_RELEASE=$RESTY_RELEASE \
        --push \
        .
